#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
changed=$(git diff --dirstat=files,0 HEAD~1 | awk '{ print $2 }' | grep -v circleci)
for dir_name in $(ls -d */ | sed s'/.$//')
do
if echo $changed | grep -w $dir_name > /dev/null; then
    docker push gettyio/$dir_name
fi
done